name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Ruff (lint)
        run: ruff check .
      - name: Pytest
        run: pytest -q
      - name: pip-audit
        run: pip-audit -r <(pip freeze) || true
      - name: Build wheel
        run: python -m build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*
