name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Ruff (lint)
        run: ruff check .
      
      - name: Pytest
        run: pytest -q

      - name: Coverage report
        run: pytest -q --maxfail=1 --disable-warnings --cov=src/github_admin_cli --cov-report=xml

      - name: pip-audit
        run: pip-audit -r <(pip freeze) || true
      
      - name: Install build tool
        run: python -m pip install --upgrade build
      
      - name: Build wheel
        run: python -m build
      
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v5
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml